name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rust-core:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Core
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  go-modules:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Build NeuroSploit
      run: cd modules/neurospoit && go build ./...
    - name: Build API-Nemesis
      run: cd modules/api-nemesis && go build ./...

  python-modules:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        cd modules/quantummapper && poetry install
        cd ../auto-pentest && poetry install
